# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/GenshinMinecraft"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://x.com/C1oudF1are"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "rss"
name = "RSS"
url = "https://blog.c1oudf1are.eu.org/index.xml"

[social.params]
icon = "brand-rss"

[[social]]
identifier = "telegram"
name = "Telegram"
url = "https://t.me/C1oudF1are"

[social.params]
icon = "brand-telegram"