name: Hugo Build

on:
  push:
    branches:
      - "*"

jobs:
  release:
    name: Hugo Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.123.0'
      - name: Build
        run: hugo --gc --logLevel debug --buildDrafts --buildExpired --buildFuture
      - name: Upload Site
        uses: actions/upload-artifact@v3
        with:
          name: Hugo-Public
          path: ./public
